export default {
  coffee_table: {
    id: 'coffee_table',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/coffee_table/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/coffee_table/2.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/coffee_table/3.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/coffee_table/4.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/coffee_table/5.jpeg`,
      // `${process.env.PUBLIC_URL}/img/living-room/coffee_table/6.jpeg`,
      // `${process.env.PUBLIC_URL}/img/living-room/coffee_table/7.jpeg`,
    ],
    name: 'Durian HENLEY Metal Coffee Table  (Finish Color - Dark Walnut)',
    price: 25935,
    averageRating: 3.9,
    totalRatings: 223,
    totalReviews: 54,
    emi: 862,
  },
  lamp: {
    id: 'lamp',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/lamp/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/lamp/2.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/lamp/3.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/lamp/4.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/lamp/5.jpeg`,
    ],
    name: 'Anasa New Modern Design Glass Table Lamp  (60.96 cm, Gold)',
    price: 7200,
    averageRating: 3.7,
    totalRatings: 23,
    totalReviews: 4,
    emi: 240,
  },
  modern_lamp: {
    id: 'modern_lamp',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/modern_lamp/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/modern_lamp/2.jpeg`,
    ],
    name: 'Stello Modern Lamp SL5004 Table Lamp  (55 cm, French Gold)',
    price: 6990,
    averageRating: 3.5,
    totalRatings: 42,
    totalReviews: 5,
    emi: 233,
  },
  round_side_table: {
    id: 'round_side_table',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/round_side_table/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/round_side_table/2.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/round_side_table/3.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/round_side_table/4.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/round_side_table/5.jpeg`,
    ],
    name: 'HomeHQ Aurora Solid Wood Side Table  (Finish Color - Brown)\n',
    price: 11250,
    averageRating: 4.1,
    totalRatings: 22,
    totalReviews: 1,
    emi: 374,
  },
  side_table: {
    id: 'side_table',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/side_table/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/side_table/2.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/side_table/3.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/side_table/4.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/side_table/5.jpeg`,
    ],
    name: 'Balaji Solid Wood Side Table  (Finish Color - Teak)',
    price: 3799,
    averageRating: 4.5,
    totalRatings: 2,
    totalReviews: 1,
    emi: 127,
  },
  sofa: {
    id: 'sofa',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/sofa/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/sofa/2.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/sofa/3.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/sofa/4.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/sofa/5.jpeg`,
    ],
    name: 'Urban Ladder Apollo Fabric 3 + 2 + 1 + 1 Pearl Sofa Set',
    price: 114996,
    averageRating: 4.2,
    totalRatings: 2,
    totalReviews: 1,
    emi: 3820,
  },
  tv_unit: {
    id: 'tv_unit',
    imageCollection: [
      `${process.env.PUBLIC_URL}/img/living-room/tv_unit/1.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/tv_unit/2.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/tv_unit/3.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/tv_unit/4.jpeg`,
      `${process.env.PUBLIC_URL}/img/living-room/tv_unit/5.jpeg`,
    ],
    name: 'Flipkart Perfect Homes PureWood Sheesham TV Entertainment Unit  (Finish Color - Dark Walnut)',
    price: 13679,
    averageRating: 4.3,
    totalRatings: 26,
    totalReviews: 9,
    emi: 1520,
  },
}